services:
  - type: web
    name: fastapi-app        
    env: docker            
    plan: free               
    dockerfilePath: ./Dockerfile  
    autoDeploy: true         
    envVars:                 
      - key: ENV
        value: production    
      - key: DATABASE_URL
        sync: false           
      - key: SECRET_KEY
        sync: false           
